# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMConnection'
    subscriptionId: '5504e78e-76df-44ff-b37e-b80c151e00b9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Main'
    location: 'UAE North'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/yanivsel/ms_work/blob/main/Microsoft/ARM/sa_template.json'
    overrideParameters: |
      -storageAccountName [yanivian1]
      -location [Main]
      -containerName [blobcontainer]
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMConnection'
    subscriptionId: '5504e78e-76df-44ff-b37e-b80c151e00b9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Main'
    location: 'UAE North'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/yanivsel/ms_work/blob/main/Microsoft/ARM/server_template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/yanivsel/ms_work/blob/main/Microsoft/ARM/server_template.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'yanivian1'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMConnection'
    subscriptionId: '5504e78e-76df-44ff-b37e-b80c151e00b9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Main'
    location: 'UAE North'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/yanivsel/ms_work/blob/main/Microsoft/ARM/sa_template.json'
    overrideParameters: |
      -storageAccountName [yanivian2]
      -location [Main]
      -containerName [blobcontainer]
    deploymentMode: 'Incremental'
